FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app:/app/streamlit

COPY streamlit ./streamlit
COPY src ./src
COPY data/raw/arrondissements_paris.geojson ./data/raw/arrondissements_paris.geojson

WORKDIR /app/streamlit

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
