apiVersion: 1

datasources:
  # C20 : Grafana utilise Prometheus comme source de donnees.
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
